site_name: fluent-python-2e
nav:
  - Home: index.md
  - About: about.md
  - Usage: usage.md
  - 读书笔记: chapters.md
  - 项目结构: structure.md
theme:
  name: "material"
  custom_dir: overrides

plugins:
- search